/**
 * Aurora Theme — two-factor checkpoint screen. Logic identical to stock.
 */
import React, { useState } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import loginCheckpoint from '@/api/auth/loginCheckpoint';
import LoginFormContainer from '@/components/auth/LoginFormContainer';
import { ActionCreator } from 'easy-peasy';
import { StaticContext } from 'react-router';
import { useFormikContext, withFormik } from 'formik';
import useFlash from '@/plugins/useFlash';
import { FlashStore } from '@/state/flashes';
import { AuroraField } from '@/aurora/components/forms';
import { AuroraButton } from '@/aurora/components/Button';

interface Values {
    code: string;
    recoveryCode: '';
}

type OwnProps = RouteComponentProps<Record<string, string | undefined>, StaticContext, { token?: string }>;

type Props = OwnProps & {
    clearAndAddHttpError: ActionCreator<FlashStore['clearAndAddHttpError']['payload']>;
};

const LoginCheckpointContainer = () => {
    const { isSubmitting, setFieldValue } = useFormikContext<Values>();
    const [isMissingDevice, setIsMissingDevice] = useState(false);

    return (
        <LoginFormContainer title="Device Checkpoint">
            <AuroraField
                name={isMissingDevice ? 'recoveryCode' : 'code'}
                label={isMissingDevice ? 'Recovery Code' : 'Authentication Code'}
                description={
                    isMissingDevice
                        ? 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.'
                        : 'Enter the two-factor token generated by your device.'
                }
                type="text"
                autoComplete="one-time-code"
                autoFocus
                inputMode="numeric"
            />
            <div style={{ marginTop: '1.25rem' }}>
                <AuroraButton size="xl" block type="submit" disabled={isSubmitting} loading={isSubmitting}>
                    Continue
                </AuroraButton>
            </div>
            <button
                type="button"
                onClick={() => {
                    setFieldValue('code', '');
                    setFieldValue('recoveryCode', '');
                    setIsMissingDevice((s) => !s);
                }}
                className="aurora-auth-alt"
            >
                {!isMissingDevice ? "I've Lost My Device" : 'I Have My Device'}
            </button>
            <Link to="/auth/login" className="aurora-auth-alt" style={{ marginTop: '0.75rem' }}>
                Return to Login
            </Link>
        </LoginFormContainer>
    );
};

const EnhancedForm = withFormik<Props, Values>({
    handleSubmit: ({ code, recoveryCode }, { setSubmitting, props: { clearAndAddHttpError, location } }) => {
        loginCheckpoint(location.state?.token || '', code, recoveryCode)
            .then((response) => {
                if (response.complete) {
                    // @ts-expect-error this is valid
                    window.location = response.intended || '/';
                    return;
                }

                setSubmitting(false);
            })
            .catch((error) => {
                console.error(error);
                setSubmitting(false);
                clearAndAddHttpError({ error });
            });
    },

    mapPropsToValues: () => ({
        code: '',
        recoveryCode: '',
    }),
})(LoginCheckpointContainer);

export default ({ history, location, ...props }: OwnProps) => {
    const { clearAndAddHttpError } = useFlash();

    if (!location.state?.token) {
        history.replace('/auth/login');

        return null;
    }

    return (
        <EnhancedForm clearAndAddHttpError={clearAndAddHttpError} history={history} location={location} {...props} />
    );
};
